### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by EugenMayer** [mortensteenrasmussen/docker-registry-manifest-cleanup#1]
Not sure how many people actually run their registry wide open, but what about supporting authentication? Thanks!

**Comment by mortensteenrasmussen** [comment]
I'll look into that ASAP. Are we talking HTTP basic auth?

**Comment by EugenMayer** [comment]
Depending on you guess basic authentication will be the common one, iam using JWT but well that's probably less spreaded. Thanks for looking into this

**Comment by krzysztof-indyk** [comment]
Basic authentication works if you pass login and password in URL

`docker run -it -v <path-to-registry>:/registry -e REGISTRY_URL=https://<login>:<pass>@<host> mortensrasmussen/docker-registry-manifest-cleanup`

**Comment by mortensteenrasmussen** [comment]
Thanks for the information, this should be added to the readme - I'll do it as soon as I have time :)

**Comment by dinoba** [comment]
I suggest this change

curl -fsS **-u user:password**  -X DELETE ${REGISTRY_URL}/v2/${repo}/manifests/sha256:${manifest} > /dev/null

passing login and pass via URL didn't work for me. 

Maybe you can add another variable and use it for **-u user:password**

**Comment by EugenMayer** [comment]
or just run sonatype nexus to have this one build in. https://github.com/EugenMayer/docker-rancher-extra-catalogs/tree/master/templates/sona-nexus

**Comment by alexpilotti** [comment]
Beside basic auth, Docker registry v2 adds token authentication which is much more flexible.
Instead of using curl to fetch a token with the proper scope and then calling the registry API, the following commit replaces curl with reg (https://github.com/jessfraz/reg) since it already provides all the boilerplate: https://github.com/mortensteenrasmussen/docker-registry-manifest-cleanup/pull/10

Example:

`docker run -it -v /opt/registry:/registry -e REGISTRY_URL=https://registry.blah.com -e CURL_INSECURE=true -e REGISTRY_USERNAME=foo -e REGISTRY_PASSWORD=bar docker-registry-manifest-cleanup
`

**Comment by mortensteenrasmussen** [comment]
Basic http auth is available now, in the new version.
