### ISSUE TITLE
Python version less error-tolerant

### ISSUE THREAD

**Issue by bard** [mortensteenrasmussen/docker-registry-manifest-cleanup#15]
For some reason (probably past cleanup attempts) some files were missing from my registry storage.

The latest version stopped right away:

``` sh
$ docker run -it -v /opt/registry:/registry -e REGISTRY_URL=http://localhost:5000 -e DRY_RUN="true" mortensrasmussen/docker-registry-manifest-cleanup:latest
Running in dry-run mode. No changes will be made.

Running against local storage
Traceback (most recent call last):
File "/docker-registry-cleanup.py", line 132, in <module>
manifest = json.loads(open("%s/sha256/%s/%s/data" % (blob_dir, shasum[0:2], shasum)).read())
FileNotFoundError: [Errno 2] No such file or directory: '/registry/docker/registry/v2/blobs/sha256/4f/4f30047314aa492e822ef44f9518a82105e7a8834db83216aa025b324aedddf2/data'
$
```

1.0.5 (pre-Python rewrite) ignored the error, did what work it could, and eventually I could clean the registry:

``` sh
$ docker run -it -v /opt/registry:/registry -e REGISTRY_URL=http://localhost:5000 -e DRY_RUN="true" mortensrasmussen/docker-registry-manifest-cleanup:1.0.5
Running in dry-run mode. Will not make any changes
cat: can't open '/registry/docker/registry/v2/blobs/sha256/09/09eeabec5c978c6ffef6a276cfc3ef4da8ef81d765ac472d81b3cf01ef907a66/data': No such file or directory
cat: can't open '/registry/docker/registry/v2/blobs/sha256/2d/2dc68d01b1e83f77b65ce3ff586cba58e3893a52ba973edc19e9dc5f958de113/data': No such file or directory
cat: can't open '/registry/docker/registry/v2/blobs/sha256/4f/4f30047314aa492e822ef44f9518a82105e7a8834db83216aa025b324aedddf2/data': No such file or directory
cat: can't open '/registry/docker/registry/v2/blobs/sha256/63/6383c42a9b53b60735ee058c874d2ea32cdd8a250ae71b1f0dbb24ef49d810b4/data': No such file or directory
cat: can't open '/registry/docker/registry/v2/blobs/sha256/ad/ad7b2a92bc7c284f46ee93a1f319ce6ab222b76fa397ed61b1f9e6e36fd06153/data': No such file or directory
cat: can't open '/registry/docker/registry/v2/blobs/sha256/b8/b89c2a0d15aa3cc67a3b7e912857ccc9f419c1f294f68971dc73fe6850a61a00/data': No such file or directory
Found 312 manifests. Starting to clean up ..not really, because dry-run.
## Doing 1 / 312
Would have run curl -fsS  -X DELETE .........
```

**Comment by mortensteenrasmussen** [comment]
Hi @bard, thanks for the report.

I can see how that is an issue, and it should be a fairly easy fix. 

The reason I didn't catch it is that in my testing I spin up new registries, push some stuff and test - this error only occurs when a registry has some corruption on the filesystem level (which is the case once in a while for long-running registries). The corruption can happen in many ways, but most likely its an unexpected shutdown of the registry during a push at some point.

I'll give it a go for a fix during the weekend, and let you know when the fix is available.

**Comment by bard** [comment]
No worries, the previous version cleaned up the registry just fine (which had grown to dangerous dimensions—thanks for this godsend!). I just reported it so that others stumbling on this might have a workaround.

**Comment by WTFKr0** [comment]
Hello,

Got same here, can we have a fix ?
Or a workaround please with the latest version ?

Thanx

**Comment by mortensteenrasmussen** [comment]
Hi, things have been a bit hectic here, so I haven't had the time to create the fix.
I don't really have a workaround unless you know your way around python and can implement the fix yourself - there needs to be a try/catch around the opening of the file on line 132 (or a check to see if the file exists). If the file doesnt exist, the manifest list logic should be skipped (lines 134-140) and the shasum should be added to the linked list (as is done on line 141).

I'll see if I can squeeze this fix in within the next few days, but I can't promise it.

**Comment by WTFKr0** [comment]
Thanx for that, i'll check if i can fix it and create a PR next
Nice to have so many details 👍

**Comment by WTFKr0** [comment]
Just sent you a PR
I test on my env (local storage) without problems

**Comment by mortensteenrasmussen** [comment]
I just created a 1.1.2beta release that should fix this issue on both local and S3 storage. @sculeb Thanks for the information, I didn't really have the time to make a yolo env var to delete the files (the script doesn't touch the filesystem as is, which i think is a good idea :) ) - If you feel like it, you're welcome to make a PR :)

`docker pull mortensrasmussen/docker-registry-manifest-cleanup:1.1.2beta` - please let me know if you experience issues, otherwise I'll promote the release in a week or so.
