### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by DeoLeung** [mortensteenrasmussen/docker-registry-manifest-cleanup#18]
```bash
$ docker run --rm -v /home/data/docker/registry:/registry -e REGISTRY_URL=https://abc.com  mortensrasmussen/docker-registry-manifest-cleanup
Traceback (most recent call last):
  File "/docker-registry-cleanup.py", line 132, in <module>
    manifest = json.loads(open("%s/sha256/%s/%s/data" % (blob_dir, shasum[0:2], shasum)).read())
FileNotFoundError: [Errno 2] No such file or directory: '/registry/docker/registry/v2/blobs/sha256/66/66387a38047c4ef8e17871d35dab749e6d9f64f27fb0ecb92c797aa391ab46d8/data'
Running against local storage
```

should I run something before to avoid missing file?

**Comment by sachinphogat** [comment]
I am also facing the same issue, using registry v2.7.1 on centos

**Comment by sunyao5588** [comment]
same issue here. any solutions?

**Comment by sculeb** [comment]
Ran into the same issue. For me it happened because something (I don't know what, tho) went wrong when a tag was deleted via the registry. This lead to the tag still being present under `/registry/v2/repositories/{repo}/{project}/_manifests/tags/{tag}/current/link` but there was no file for the shasum given inside the link-file under `/registry/docker/registry/v2/blobs/sha256/{shasum[0:2]}/{shasum}/data`.

`grep -rnw '/registry/docker/registry/v2/repositories/' -e 'sha256:{shasum}'` helped me find the tag, that was existing under repos but not under blobs. Deleting it solved my problem.

For an actual fix for the script: Not sure what the desired behaviour is in this case. Maybe allowing automated deletion if data of a tag is not found, configurable via env var? Otherwise ignoring with a warn log?

**Comment by mortensteenrasmussen** [comment]
I just created a 1.1.2beta release that should fix this issue on both local and S3 storage. @sculeb Thanks for the information, I didn't really have the time to make a yolo env var to delete the files (the script doesn't touch the filesystem as is, which i think is a good idea :) ) - If you feel like it, you're welcome to make a PR :)

`docker pull mortensrasmussen/docker-registry-manifest-cleanup:1.1.2beta` - please let me know if you experience issues, otherwise I'll promote the release in a week or so.
