### ISSUE TITLE
Garbage collection after cleanup

### ISSUE THREAD

**Issue by vladkras** [mortensteenrasmussen/docker-registry-manifest-cleanup#9]
First of all, thank you! You saved my day. I've run cleanup with success, but the result was
```
$ docker run -it -v $(pwd)/registry:/registry -e REGISTRY_URL=http://<user>:<password>@<host>:5000 mortensrasmussen/docker-registry-manifest-cleanup
Found 201 manifests. Starting to clean up
## Doing 1 / 201
...
## Doing 201 / 201
Job done, Cleaned 201 of 201 manifests.
Disk usage before and after:
/dev/vda9                55.8G     52.3G      1.1G  98% /registry

/dev/vda9                55.8G     52.6G    883.6M  98% /registry
```
so, actually no cleaning at all until I run gc by myself
```
docker exec -it <registry_container> bin/registry garbage-collect /etc/docker/registry/config.yml
```
this freed 26G of space.
Maybe consider adding gc to your script?

**Comment by mortensteenrasmussen** [comment]
Hi,

I'm happy you could use it!

Yes, the disk usage output is very misleading as it will always show the same before and after.

It's written in the README.md that you need to run a GC after running this, but I can see that it gets easily lost/missed when looking at the readme.

I don't want to mess around with finding the correct container and exec'ing into that, which is why it's not done automatically. Without knowing peoples environments, there's a risk to mess something up and I don't want to take that chance :)

**Comment by vladkras** [comment]
Oh, yes, I see now. You did write it in the begining of README, My bad.
Nevertheless, you can add this advice right after or instead "disk usage" output if you wish.

Unfortunatelly, one of my images was broken during the cleanup but it's not reproducible and could be my mistake with inaccurate deleteing of another tags: I can push an image with tag but I can't pull it. So I had to delete this image and all tags completely and now it works as expected.

Did something like this occured with another registries? I'll stay in touch and report about any other problems.

**Comment by chino** [comment]
Has anyone seen GC not actually remove anything?

**Comment by mortensteenrasmussen** [comment]
Did the script output suggest that it removed entries?

Something like the following:
```
Job done, Cleaned 201 of 201 manifests.
```

If that is the case, then the GC should certainly clean that up. 

If you still have issues please open another issue so we can track that separately.

**Comment by mortensteenrasmussen** [comment]
I added a message saying to run a GC manually now.
